"""Deterministic sample repertoire for examples, tests, and CLI demos."""

# ruff: noqa: E501
from dataclasses import replace
from datetime import date
from decimal import Decimal

from open_mic_lab.domain import (
    AccompanimentTask,
    Arrangement,
    ArrangementFlexibility,
    AudienceFamiliarity,
    AudienceInteraction,
    Automaticity,
    CommunicationPlan,
    CoordinationProfile,
    Difficulty,
    EmotionalTone,
    EnergyLevel,
    Genre,
    Instrument,
    IntroductionPurpose,
    Mood,
    PerformanceFlow,
    PerformanceRole,
    PerformanceStatus,
    PerformanceVersion,
    PerformerBehavior,
    PracticeSession,
    Repertoire,
    SetList,
    SetTransition,
    Song,
    SongSelectionProfile,
    SpokenIntroduction,
    StageMoment,
    StorySegment,
    TransitionEnergyEffect,
    TransitionKind,
    Venue,
    VenueType,
    VocalRange,
    VocalTask,
)


def build_sample_repertoire() -> Repertoire:
    """Build seven songs and ten performance versions with deterministic ordering."""
    rep = Repertoire()
    songs = (
        Song(
            "river-road",
            "River Road at Dusk",
            "Mara Vale",
            Genre.FOLK,
            "G",
            92,
            "4/4",
            Mood.REFLECTIVE,
            Decimal("3"),
            Decimal("8"),
            Decimal("2"),
        ),
        Song(
            "lantern-swing",
            "Lantern Swing",
            "Public Domain Style",
            Genre.JAZZ,
            "F",
            132,
            "4/4",
            Mood.PLAYFUL,
            Decimal("5"),
            Decimal("4"),
            Decimal("6"),
        ),
        Song(
            "harbor-bell",
            "Harbor Bell",
            "Traditional",
            Genre.TRADITIONAL,
            "D",
            104,
            "3/4",
            Mood.WARM,
            Decimal("8"),
            Decimal("6"),
            Decimal("7"),
        ),
        Song(
            "blue-ticket",
            "Blue Ticket Blues",
            "Jonas Reed",
            Genre.BLUES,
            "E",
            88,
            "4/4",
            Mood.MELANCHOLY,
            Decimal("4"),
            Decimal("5"),
            Decimal("5"),
        ),
        Song(
            "window-original",
            "Window Light",
            "Learner Original",
            Genre.ORIGINAL,
            "A",
            76,
            "4/4",
            Mood.RESOLUTE,
            Decimal("1"),
            Decimal("9"),
            Decimal("3"),
        ),
        Song(
            "last-train-home",
            "Last Train Home",
            "Fictional Standard",
            Genre.POP,
            "C",
            148,
            "4/4",
            Mood.ENERGETIC,
            Decimal("7"),
            Decimal("5"),
            Decimal("9"),
        ),
        Song(
            "paper-kite",
            "Paper Kite Parade",
            "Public Domain Style",
            Genre.POP,
            "Bb",
            116,
            "4/4",
            Mood.PLAYFUL,
            Decimal("6"),
            Decimal("3"),
            Decimal("8"),
        ),
    )
    for song in songs:
        rep.add_song(song)
    versions = (
        PerformanceVersion(
            "river-guitar-original",
            "river-road",
            "G",
            92,
            Instrument.GUITAR_VOCAL,
            Difficulty.MODERATE,
            Decimal("6"),
            Decimal("7"),
            Decimal("7"),
            Decimal("5"),
            PerformanceStatus.DEVELOPING,
            20,
            date_added=date(2026, 6, 1),
            last_practiced=date(2026, 6, 20),
            maintenance_interval_days=21,
            total_practice_sessions=2,
            target_readiness=80,
            preferred_venue_types=(VenueType.OPEN_MIC,),
            notes="Original key and tempo.",
        ),
        PerformanceVersion(
            "river-guitar-lowered",
            "river-road",
            "E",
            84,
            Instrument.GUITAR_VOCAL,
            Difficulty.SIMPLE,
            Decimal("8"),
            Decimal("8"),
            Decimal("8"),
            Decimal("7"),
            PerformanceStatus.NEARLY_READY,
            15,
            date_added=date(2026, 6, 10),
            last_practiced=date(2026, 7, 25),
            last_performed=date(2026, 7, 28),
            maintenance_interval_days=14,
            total_practice_sessions=5,
            total_performances=1,
            total_audience_responses=6,
            target_readiness=85,
            preferred_venue_types=(VenueType.CAFE, VenueType.OPEN_MIC),
            average_confidence=Decimal("8"),
            notes="Lowered key for vocal comfort.",
        ),
        PerformanceVersion(
            "lantern-piano",
            "lantern-swing",
            "F",
            126,
            Instrument.PIANO_VOCAL,
            Difficulty.CHALLENGING,
            Decimal("6"),
            Decimal("6"),
            Decimal("5"),
            Decimal("5"),
            PerformanceStatus.LEARNING,
            25,
            date_added=date(2026, 7, 1),
            last_practiced=date(2026, 7, 3),
            maintenance_interval_days=10,
            total_practice_sessions=1,
            target_readiness=75,
            preferred_venue_types=(VenueType.HOUSE_CONCERT,),
        ),
        PerformanceVersion(
            "harbor-guitar",
            "harbor-bell",
            "D",
            104,
            Instrument.GUITAR_VOCAL,
            Difficulty.SIMPLE,
            Decimal("9"),
            Decimal("9"),
            Decimal("8"),
            Decimal("8"),
            PerformanceStatus.PERFORMANCE_READY,
            10,
            date_added=date(2026, 5, 1),
            last_practiced=date(2026, 8, 1),
            last_performed=date(2026, 7, 28),
            maintenance_interval_days=21,
            total_practice_sessions=6,
            total_performances=3,
            total_audience_responses=12,
            target_readiness=85,
            preferred_venue_types=(VenueType.CAFE, VenueType.OPEN_MIC),
            preferred_performance_role=PerformanceRole.OPENER,
            average_confidence=Decimal("8.5"),
        ),
        PerformanceVersion(
            "blue-ticket-guitar",
            "blue-ticket",
            "E",
            88,
            Instrument.GUITAR_VOCAL,
            Difficulty.MODERATE,
            Decimal("7"),
            Decimal("6"),
            Decimal("6"),
            Decimal("7"),
            PerformanceStatus.DEVELOPING,
            15,
            date_added=date(2026, 6, 15),
            last_practiced=date(2026, 7, 18),
            maintenance_interval_days=14,
            total_practice_sessions=3,
            target_readiness=80,
            preferred_venue_types=(VenueType.OPEN_MIC,),
        ),
        PerformanceVersion(
            "window-piano",
            "window-original",
            "A",
            72,
            Instrument.PIANO_VOCAL,
            Difficulty.MODERATE,
            Decimal("8"),
            Decimal("7"),
            Decimal("7"),
            Decimal("8"),
            PerformanceStatus.NEARLY_READY,
            30,
            date_added=date(2026, 6, 25),
            last_practiced=date(2026, 7, 31),
            maintenance_interval_days=14,
            total_practice_sessions=4,
            total_performances=1,
            target_readiness=85,
            preferred_venue_types=(VenueType.HOUSE_CONCERT,),
            preferred_performance_role=PerformanceRole.CENTERPIECE,
            average_confidence=Decimal("7.5"),
        ),
        PerformanceVersion(
            "train-guitar-closer",
            "last-train-home",
            "C",
            148,
            Instrument.GUITAR_VOCAL,
            Difficulty.SIMPLE,
            Decimal("9"),
            Decimal("8"),
            Decimal("9"),
            Decimal("8"),
            PerformanceStatus.PERFORMANCE_READY,
            12,
            VocalRange.from_strings("A2", "C#4"),
            EnergyLevel.VERY_HIGH,
            (PerformanceRole.CLOSER, PerformanceRole.ENCORE),
            Decimal("6"),
            _flex(Instrument.GUITAR_VOCAL),
            205,
            date_added=date(2026, 5, 20),
            last_practiced=date(2026, 7, 26),
            last_performed=date(2026, 7, 28),
            maintenance_interval_days=14,
            total_practice_sessions=5,
            total_performances=2,
            total_audience_responses=9,
            target_readiness=90,
            preferred_venue_types=(VenueType.OPEN_MIC, VenueType.CAFE),
            preferred_performance_role=PerformanceRole.CLOSER,
            average_confidence=Decimal("8.5"),
        ),
        PerformanceVersion(
            "paper-ukulele-opener",
            "paper-kite",
            "Bb",
            112,
            Instrument.UKULELE_VOCAL,
            Difficulty.SIMPLE,
            Decimal("9"),
            Decimal("9"),
            Decimal("8"),
            Decimal("8"),
            PerformanceStatus.NEARLY_READY,
            8,
            VocalRange.from_strings("Bb2", "D4"),
            EnergyLevel.MEDIUM,
            (PerformanceRole.OPENER, PerformanceRole.AUDIENCE_PARTICIPATION),
            Decimal("3"),
            _flex(Instrument.UKULELE_VOCAL, Instrument.GUITAR_VOCAL),
            180,
            date_added=date(2026, 7, 5),
            last_practiced=date(2026, 7, 22),
            maintenance_interval_days=10,
            total_practice_sessions=3,
            target_readiness=85,
            preferred_venue_types=(VenueType.CAFE, VenueType.COMMUNITY_EVENT),
            preferred_performance_role=PerformanceRole.OPENER,
            average_confidence=Decimal("8"),
        ),
        PerformanceVersion(
            "lantern-piano-simpler",
            "lantern-swing",
            "E",
            116,
            Instrument.PIANO_VOCAL,
            Difficulty.MODERATE,
            Decimal("7"),
            Decimal("8"),
            Decimal("7"),
            Decimal("7"),
            PerformanceStatus.NEARLY_READY,
            12,
            VocalRange.from_strings("B2", "E4"),
            EnergyLevel.HIGH,
            (PerformanceRole.CONTRAST, PerformanceRole.EARLY_SET),
            Decimal("5"),
            _flex(Instrument.PIANO_VOCAL),
            190,
            date_added=date(2026, 7, 10),
            last_practiced=date(2026, 8, 2),
            maintenance_interval_days=10,
            total_practice_sessions=4,
            target_readiness=85,
            preferred_venue_types=(VenueType.HOUSE_CONCERT,),
            average_confidence=Decimal("7"),
        ),
        PerformanceVersion(
            "window-guitar-original-feature",
            "window-original",
            "G",
            76,
            Instrument.GUITAR_VOCAL,
            Difficulty.CHALLENGING,
            Decimal("5"),
            Decimal("5"),
            Decimal("6"),
            Decimal("5"),
            PerformanceStatus.DEVELOPING,
            35,
            VocalRange.from_strings("B2", "F4"),
            EnergyLevel.LOW,
            (PerformanceRole.ORIGINAL_FEATURE, PerformanceRole.CENTERPIECE),
            Decimal("10"),
            _flex(Instrument.GUITAR_VOCAL, Instrument.PIANO_VOCAL),
            240,
            date_added=date(2026, 7, 12),
            last_practiced=date(2026, 7, 14),
            maintenance_interval_days=7,
            total_practice_sessions=2,
            target_readiness=80,
            preferred_venue_types=(VenueType.CAFE, VenueType.HOUSE_CONCERT),
            preferred_performance_role=PerformanceRole.ORIGINAL_FEATURE,
            average_confidence=Decimal("5.5"),
            setup_requirements=("capo",),
        ),
    )
    for version in versions:
        rep.add_performance_version(
            replace(version, arrangement_identifier=f"{version.identifier}-arrangement")
        )

    arrangements = (
        Arrangement(
            "river-guitar-original-arrangement",
            "Original guitar arrangement",
            "river-guitar-original",
            Instrument.GUITAR_VOCAL,
            (),
            "G",
            92,
            "folk ballad",
            "four-bar fingerpicked intro",
            "quiet tag ending",
            ("Intro", "Verse 1", "Chorus", "Verse 2", "Bridge", "Final Chorus"),
            2,
            True,
            (),
            (),
            0,
            "gentle build",
            "Baseline recording-inspired guitar/vocal arrangement.",
        ),
        Arrangement(
            "river-guitar-lowered-arrangement",
            "Lower-key guitar arrangement",
            "river-guitar-lowered",
            Instrument.GUITAR_VOCAL,
            (),
            "E",
            84,
            "coffeehouse folk",
            "two-bar intro",
            "soft ritard ending",
            ("Intro", "Verse 1", "Chorus", "Verse 2", "Final Chorus"),
            2,
            False,
            (),
            (),
            1,
            "warm and steady",
            "Lower key and slower tempo for vocal comfort.",
        ),
        Arrangement(
            "lantern-piano-arrangement",
            "Original piano swing arrangement",
            "lantern-piano",
            Instrument.PIANO_VOCAL,
            (),
            "F",
            126,
            "swing",
            "eight-bar stride intro",
            "button ending",
            ("Intro", "Verse 1", "Chorus", "Verse 2", "Bridge", "Final Chorus"),
            2,
            True,
            ("piano solo",),
            (),
            0,
            "bright accents",
            "Fuller piano arrangement.",
        ),
        Arrangement(
            "harbor-guitar-arrangement",
            "Guitar waltz arrangement",
            "harbor-guitar",
            Instrument.GUITAR_VOCAL,
            (),
            "D",
            104,
            "waltz",
            "one-measure pickup",
            "simple held final chord",
            ("Intro", "Verse 1", "Chorus", "Verse 2", "Final Chorus"),
            2,
            False,
            (),
            ("invite humming on final chorus",),
            1,
            "warm steady lift",
        ),
        Arrangement(
            "blue-ticket-guitar-arrangement",
            "Blues guitar arrangement",
            "blue-ticket-guitar",
            Instrument.GUITAR_VOCAL,
            (),
            "E",
            88,
            "shuffle blues",
            "turnaround intro",
            "twelve-bar tag",
            ("Intro", "Verse 1", "Chorus", "Verse 2", "Guitar break", "Final Chorus"),
            2,
            False,
            ("Guitar break",),
            (),
            0,
            "gritty mid-level",
        ),
        Arrangement(
            "window-piano-arrangement",
            "Original piano arrangement",
            "window-piano",
            Instrument.PIANO_VOCAL,
            (),
            "A",
            72,
            "reflective piano",
            "rubato piano intro",
            "long suspended ending",
            ("Intro", "Verse 1", "Chorus", "Verse 2", "Bridge", "Final Chorus", "Extended Ending"),
            2,
            True,
            (),
            (),
            0,
            "quiet to resolute",
            "Original piano-led version.",
        ),
        Arrangement(
            "train-guitar-closer-arrangement",
            "Guitar closer arrangement",
            "train-guitar-closer",
            Instrument.GUITAR_VOCAL,
            (),
            "C",
            148,
            "driving pop",
            "count-in riff",
            "big final stop",
            ("Intro", "Verse 1", "Chorus", "Verse 2", "Bridge", "Final Chorus"),
            3,
            True,
            ("instrumental break",),
            ("clap on choruses",),
            0,
            "high-energy lift",
        ),
        Arrangement(
            "paper-ukulele-opener-arrangement",
            "Audience participation arrangement",
            "paper-ukulele-opener",
            Instrument.UKULELE_VOCAL,
            (Instrument.GUITAR_VOCAL,),
            "Bb",
            112,
            "bright ukulele pop",
            "spoken clap setup",
            "sing-along ending",
            ("Intro", "Verse 1", "Chorus", "Verse 2", "Final Chorus", "Audience Refrain"),
            3,
            False,
            (),
            ("teach refrain before final chorus",),
            1,
            "playful swell",
        ),
        Arrangement(
            "lantern-piano-simpler-arrangement",
            "Simplified piano arrangement",
            "lantern-piano-simpler",
            Instrument.PIANO_VOCAL,
            (),
            "E",
            116,
            "coffeehouse swing",
            "short vamp",
            "simple button ending",
            ("Intro", "Verse 1", "Chorus", "Verse 2", "Final Chorus"),
            2,
            False,
            (),
            (),
            2,
            "controlled bright lift",
            "Simplified piano arrangement.",
        ),
        Arrangement(
            "window-guitar-original-feature-arrangement",
            "Guitar original feature arrangement",
            "window-guitar-original-feature",
            Instrument.GUITAR_VOCAL,
            (),
            "G",
            76,
            "coffeehouse arrangement",
            "story-led intro",
            "audience sing-along ending",
            (
                "Intro",
                "Verse 1",
                "Chorus",
                "Verse 2",
                "Instrumental",
                "Final Chorus",
                "Extended Ending",
            ),
            2,
            False,
            ("Instrumental",),
            ("repeat last line with audience",),
            1,
            "intimate to open",
            "Coffeehouse guitar arrangement.",
        ),
    )
    for arrangement in arrangements:
        rep.add_arrangement(arrangement)
    return rep


def sample_practice_sessions() -> tuple[PracticeSession, ...]:
    """Return deterministic practice evidence."""
    return (
        PracticeSession(
            "practice-river-1",
            "river-guitar-lowered",
            date(2026, 7, 20),
            35,
            82,
            4,
            Decimal("8"),
            Decimal("8"),
            Decimal("8"),
            Decimal("7"),
        ),
        PracticeSession(
            "practice-river-2",
            "river-guitar-lowered",
            date(2026, 7, 25),
            30,
            84,
            3,
            Decimal("8"),
            Decimal("8"),
            Decimal("8"),
            Decimal("7"),
        ),
        PracticeSession(
            "practice-train-1",
            "train-guitar-closer",
            date(2026, 7, 26),
            45,
            148,
            2,
            Decimal("9"),
            Decimal("9"),
            Decimal("8"),
            Decimal("8"),
        ),
    )


def sample_venue() -> Venue:
    """Return a sample open-mic venue."""
    return Venue(
        "corner-cafe", "Corner Cafe Open Mic", VenueType.OPEN_MIC, 45, Decimal("6"), True, True, 15
    )


def sample_setlist() -> SetList:
    """Return a sample 15-minute set."""
    return SetList(
        "sample-15",
        "Three-song contrast set",
        ("harbor-guitar", "window-piano", "train-guitar-closer"),
        15,
        "corner-cafe",
        sample_set_transitions(),
    )


def sample_set_transitions() -> tuple[SetTransition, ...]:
    """Return deterministic transitions for Chapter 3."""
    return (
        SetTransition(
            "opening-remarks",
            TransitionKind.SPOKEN_INTRODUCTION,
            30,
            TransitionEnergyEffect.LIFT,
            "Opening remarks",
        ),
        SetTransition(
            "window-story",
            TransitionKind.STORY,
            40,
            TransitionEnergyEffect.RESET,
            "Story about changing light",
            "harbor-guitar",
        ),
        SetTransition(
            "closing-thanks",
            TransitionKind.SPOKEN_INTRODUCTION,
            20,
            TransitionEnergyEffect.HOLD,
            "Closing thanks",
            "train-guitar-closer",
        ),
    )


def sample_set_scenarios() -> dict[str, SetList]:
    """Return deterministic Chapter 3 set-building scenarios."""
    return {
        "coffeehouse-15": sample_setlist(),
        "listening-room": SetList(
            "listening-room-set",
            "Listening room story arc",
            (
                "river-guitar-lowered",
                "window-piano",
                "lantern-piano-simpler",
                "train-guitar-closer",
            ),
            20,
            "listening-room",
            (
                SetTransition(
                    "opening-context",
                    TransitionKind.STORY,
                    45,
                    TransitionEnergyEffect.HOLD,
                    "Opening context",
                ),
                SetTransition(
                    "piano-change",
                    TransitionKind.INSTRUMENT_CHANGE,
                    45,
                    TransitionEnergyEffect.RESET,
                    "Move to piano",
                    "river-guitar-lowered",
                    ("piano bench",),
                ),
                SetTransition(
                    "final-setup",
                    TransitionKind.QUICK_SEGUE,
                    15,
                    TransitionEnergyEffect.LIFT,
                    "Quick lift into closer",
                    "lantern-piano-simpler",
                ),
            ),
        ),
        "church-special": SetList(
            "church-special",
            "Church special music",
            ("harbor-guitar", "river-guitar-lowered"),
            10,
            "corner-cafe",
            (
                SetTransition(
                    "quiet-opening",
                    TransitionKind.SILENCE,
                    10,
                    TransitionEnergyEffect.HOLD,
                    "Quiet preparation",
                ),
            ),
        ),
        "first-open-mic": SetList(
            "first-open-mic",
            "First open mic",
            ("paper-ukulele-opener", "harbor-guitar", "train-guitar-closer"),
            12,
            "corner-cafe",
            sample_set_transitions()[:1],
        ),
        "experienced-performer": SetList(
            "experienced-performer",
            "Experienced performer contrast set",
            (
                "paper-ukulele-opener",
                "blue-ticket-guitar",
                "window-guitar-original-feature",
                "train-guitar-closer",
            ),
            18,
            "corner-cafe",
            (
                SetTransition(
                    "experienced-opening",
                    TransitionKind.AUDIENCE_PARTICIPATION,
                    20,
                    TransitionEnergyEffect.LIFT,
                    "Invite the room in",
                ),
                SetTransition(
                    "original-context",
                    TransitionKind.STORY,
                    35,
                    TransitionEnergyEffect.RESET,
                    "Introduce the original",
                    "blue-ticket-guitar",
                ),
                SetTransition(
                    "closer-segue",
                    TransitionKind.QUICK_SEGUE,
                    10,
                    TransitionEnergyEffect.LIFT,
                    "Lift into the closer",
                    "window-guitar-original-feature",
                ),
            ),
        ),
    }


# Chapter 1 deterministic song-selection scenarios and expanded repertoire.


def _flex(
    *instruments: Instrument, transpose: bool = True, simplify: bool = True
) -> ArrangementFlexibility:
    return ArrangementFlexibility(transpose, simplify, True, instruments, True, True)


def sample_selection_scenarios() -> dict[str, SongSelectionProfile]:
    """Return named Chapter 1 song-selection scenarios."""
    return {
        "coffeehouse": SongSelectionProfile(
            "coffeehouse",
            "Familiar coffeehouse audience",
            "developing",
            Instrument.GUITAR_VOCAL,
            VocalRange.from_strings("A2", "D4"),
            Difficulty.MODERATE,
            Mood.WARM,
            EnergyLevel.MEDIUM,
            (Decimal("5"), Decimal("9")),
            True,
            Decimal("6"),
            Decimal("5"),
            True,
            True,
            PerformanceRole.OPENER,
            "corner-cafe",
            15,
            VocalRange.from_strings("G2", "E4"),
            (Instrument.GUITAR_VOCAL, Instrument.UKULELE_VOCAL, Instrument.A_CAPPELLA),
        ),
        "listening-room": SongSelectionProfile(
            "listening-room",
            "Quiet listening room",
            "intermediate",
            Instrument.PIANO_VOCAL,
            VocalRange.from_strings("G2", "F4"),
            Difficulty.CHALLENGING,
            Mood.REFLECTIVE,
            EnergyLevel.LOW,
            (Decimal("1"), Decimal("7")),
            False,
            Decimal("2"),
            Decimal("9"),
            True,
            True,
            PerformanceRole.CENTERPIECE,
            "listening-room",
            20,
            available_instruments=(Instrument.PIANO_VOCAL, Instrument.GUITAR_VOCAL),
            weights={
                **DEFAULT_SCENARIO_WEIGHTS,
                "connection": Decimal("0.18"),
                "audience": Decimal("0.06"),
            },
        ),
        "first-performance": SongSelectionProfile(
            "first-performance",
            "First-time performer",
            "beginner",
            Instrument.GUITAR_VOCAL,
            VocalRange.from_strings("A2", "C#4"),
            Difficulty.SIMPLE,
            Mood.WARM,
            EnergyLevel.MEDIUM,
            (Decimal("5"), Decimal("10")),
            True,
            Decimal("5"),
            Decimal("4"),
            True,
            True,
            PerformanceRole.OPENER,
            "corner-cafe",
            10,
            VocalRange.from_strings("A2", "D4"),
            (Instrument.GUITAR_VOCAL, Instrument.UKULELE_VOCAL),
            weights={
                **DEFAULT_SCENARIO_WEIGHTS,
                "vocal": Decimal("0.24"),
                "readiness": Decimal("0.22"),
                "accompaniment": Decimal("0.16"),
            },
        ),
    }


DEFAULT_SCENARIO_WEIGHTS = {
    "vocal": Decimal("0.18"),
    "accompaniment": Decimal("0.12"),
    "readiness": Decimal("0.16"),
    "audience": Decimal("0.10"),
    "connection": Decimal("0.12"),
    "venue": Decimal("0.08"),
    "role": Decimal("0.08"),
    "energy": Decimal("0.07"),
    "flexibility": Decimal("0.05"),
    "preference": Decimal("0.04"),
}


def sample_selection_venue(identifier: str) -> Venue:
    """Return the venue for a Chapter 1 scenario."""
    if identifier == "listening-room":
        return Venue(
            "listening-room",
            "Quiet Listening Room",
            VenueType.HOUSE_CONCERT,
            30,
            Decimal("3"),
            True,
            True,
            20,
        )
    return sample_venue()


def sample_coordination_profile() -> CoordinationProfile:
    """Return a deterministic Chapter 5 singing-while-playing profile."""
    return CoordinationProfile(
        "window-piano-coordination",
        VocalTask(lyric_familiarity=5, vocal_confidence=6, breathing_complexity=6),
        AccompanimentTask(
            accompaniment_difficulty=7,
            arrangement_complexity=8,
            chord_transition_security=5,
            rhythm_consistency=6,
        ),
        Automaticity(accompaniment=3, lyrics=4, coordination=2),
        tempo_bpm=72,
        target_tempo_bpm=72,
        hand_voice_independence=4,
        recent_practice_minutes=40,
    )


def sample_communication_plan() -> CommunicationPlan:
    """Build the deterministic Chapter 7 stage-presence communication plan."""
    introductions = (
        SpokenIntroduction(
            "intro-river",
            "river-guitar-lowered",
            IntroductionPurpose.CONTEXT,
            18,
            EmotionalTone.WARM,
            AudienceFamiliarity.MEDIUM,
            "begin with settled guitar pulse",
        ),
        SpokenIntroduction(
            "intro-window",
            "window-guitar",
            IntroductionPurpose.CONNECTION,
            28,
            EmotionalTone.VULNERABLE,
            AudienceFamiliarity.LOW,
            "name the first chord clearly",
            StorySegment("writing the song after a difficult week", 35, True, True),
        ),
        SpokenIntroduction(
            "intro-harbor",
            "harbor-guitar",
            IntroductionPurpose.PARTICIPATION,
            16,
            EmotionalTone.WARM,
            AudienceFamiliarity.HIGH,
            "invite gentle final refrain",
        ),
    )
    interactions = (
        AudienceInteraction(
            "opening-thanks",
            StageMoment.BEFORE_SET,
            "Thank the host and make brief eye contact with the room.",
            12,
            2,
        ),
    )
    flow = PerformanceFlow(
        silence_between_songs_seconds=(10, 32),
        transition_smoothness=6,
        confidence_continuity=7,
        eye_contact_opportunities=4,
        storytelling_opportunities=2,
        recovery_plan="Breathe, smile, re-enter at the next lyric or chord change.",
        behaviors=(
            PerformerBehavior.GROUNDED_POSTURE,
            PerformerBehavior.EYE_CONTACT,
            PerformerBehavior.RECOVERY_BREATH,
        ),
    )
    return CommunicationPlan(
        "chapter-seven-baseline",
        "coffeehouse-15",
        150,
        introductions,
        interactions,
        flow,
        "Educational sample: suggestions are prompts, not rules.",
    )
